# Generated by Django 4.0.5 on 2022-06-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=200)),
                ('sector_ln', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pendientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_pendiente', models.CharField(max_length=200)),
                ('descripcion_pendiente', models.CharField(max_length=200)),
                ('tiempo_destinado', models.IntegerField(default=0)),
            ],
        ),
    ]
