# Generated by Django 4.0.5 on 2022-06-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_pendiente', models.CharField(max_length=200)),
                ('descripcion_pendiente', models.CharField(max_length=200)),
                ('tiempo_destinado', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.RenameModel(
            old_name='Empresas',
            new_name='Empresa',
        ),
        migrations.DeleteModel(
            name='Pendientes',
        ),
    ]
