# Generated by Django 4.0.5 on 2022-06-19 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_pendiente_rename_empresas_empresa_delete_pendientes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendiente',
            name='pub_date',
        ),
    ]
